select top 10 * from customer

--1. Total revenue generated by male vs female customers
select gender, sum(purchase_amount) as revenue
from customer
group by gender

-- 2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id , purchase_amount 
from customer 
where purchase_amount > (select avg(purchase_amount) from customer) and discount_applied='Yes'

-- 3. Which are the top 5 products with the highest average review rating?
select top 5 item_purchased , round(avg(review_rating),2) as 'average_review_rating'
from customer
group by item_purchased
order by avg(review_rating) desc

-- 4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select round(avg(purchase_amount),2), shipping_type 
from customer 
where shipping_type in ('Standard','Express') 
group by shipping_type

-- 5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select 
subscription_status ,
count(customer_id) as total_customers, 
round(avg(purchase_amount),2) as average_revenue,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue , average_revenue desc

-- 6. Which 5 products have the highest percentage of purchases with discounts applied?
-- will help us to know which products heavily relies on discount to get purchased
select top 5 item_purchased, 
round((100*sum(case when discount_applied = 'Yes' then 1 else 0 end )/count(*) ),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc

-- 7.Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment
with customer_type as(
select customer_id,
previous_purchases,
case
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customer

)
select customer_segment,
count(*) as 'Number of customers'
from customer_type 
group by customer_segment
order by [Number of customers] desc

-- 8. What are the top 3 most purchased products within each category? 
with item_counts as (
select 
category,
item_purchased,
count(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id) desc) as item_ranks
from customer
group by category,item_purchased 
)
select
category,
item_ranks , 
item_purchased, 
total_orders
from item_counts
where item_ranks <=3

-- 9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select 
subscription_status,
count(customer_id) as repeat_buyers
from customer 
where previous_purchases > 5
group by subscription_status

-- 10.  What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS revenue_contribution
FROM customer
GROUP BY age_group
ORDER BY revenue_contribution DESC;

SELECT 
    age_group,
    SUM(purchase_amount) AS revenue_contribution,
    ROUND(100.0 * SUM(purchase_amount) / SUM(SUM(purchase_amount)) OVER(), 2) AS percent_of_total
FROM customer
GROUP BY age_group
ORDER BY revenue_contribution DESC;

